name: processing
channels:
  - MRtrix3
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2022.9.24=ha878542_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.7.1=h6a678d5_0
  - fftw=3.3.10=nompi_h77c792f_102
  - fontconfig=2.14.1=h52c9d5c_1
  - freetype=2.10.4=h0708190_1
  - glib=2.69.1=he621ea3_2
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=hf484d3e_1000
  - jpeg=9e=h166bdaf_1
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20230828=h5eee18b_0
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=11.2.0=h1234567_1
  - libllvm10=10.0.1=he513fc3_3
  - libpng=1.6.37=h21135ba_2
  - libpq=12.20=hdbd6064_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.2.0=hf544144_3
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mrtrix3=3.0.4=h2bc3f7f_0
  - ncurses=6.4=h6a678d5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pcre=8.45=h9c3ff4c_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.13=h1a3bd86_0
  - qt=5.15.9=h06a4308_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==2.3.0
    - acres==0.5.0
    - antspynet==0.2.9
    - antspyx==0.5.4
    - astunparse==1.6.3
    - attrs==25.3.0
    - bids-validator==1.14.7.post0
    - bidsschematools==1.0.10
    - bokeh==3.6.3
    - certifi==2025.6.15
    - charset-normalizer==3.4.2
    - ci-info==0.3.0
    - click==8.2.1
    - contourpy==1.3.2
    - cycler==0.12.1
    - dcmstack==0.9.0
    - docopt==0.6.2
    - etelemetry==0.3.1
    - filelock==3.18.0
    - flatbuffers==25.2.10
    - fonttools==4.58.4
    - formulaic==1.1.1
    - frozendict==2.4.6
    - fsspec==2025.5.1
    - gast==0.6.0
    - google-pasta==0.2.0
    - greenlet==3.2.3
    - grpcio==1.73.0
    - h5py==3.14.0
    - heudiconv==1.3.3
    - idna==3.10
    - ihmt-proc==0.1.dev31+g1c6f74a
    - imageio==2.37.0
    - importlib-resources==6.5.2
    - interface-meta==1.3.0
    - jinja2==3.1.6
    - joblib==1.5.1
    - keras==3.10.0
    - kiwisolver==1.4.8
    - latexcodec==3.0.0
    - lazy-loader==0.4
    - libclang==18.1.1
    - looseversion==1.3.0
    - lxml==5.4.0
    - mapca==0.0.5
    - markdown==3.8
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.3
    - mdurl==0.1.2
    - migas==0.4.0
    - ml-dtypes==0.4.1
    - namex==0.1.0
    - networkx==3.5
    - nibabel==5.3.2
    - nilearn==0.11.1
    - nipype==1.10.0
    - nireports==25.2.0
    - nitransforms==25.0.0
    - niworkflows==1.13.5
    - num2words==0.5.14
    - numpy==1.26.4
    - opt-einsum==3.4.0
    - optree==0.16.0
    - packaging==25.0
    - pandas==2.2.3
    - patsy==1.0.1
    - pillow==11.2.1
    - protobuf==4.25.8
    - prov==2.0.2
    - puremagic==1.29
    - pybids==0.19.0
    - pybtex==0.24.0
    - pybtex-apa-style==1.3
    - pydicom==3.0.1
    - pydot==4.0.0
    - pygments==2.19.1
    - pylibjpeg-libjpeg==2.2.0
    - pymp2rage==0.1.dev93+g0e419f8
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - rdflib==7.1.4
    - requests==2.32.4
    - rich==14.0.0
    - robustica==0.1.4
    - scikit-image==0.25.2
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - sdcflows==2.13.1
    - seaborn==0.13.2
    - setuptools==78.1.1
    - simplejson==3.20.1
    - six==1.17.0
    - sqlalchemy==2.0.41
    - statsmodels==0.14.4
    - svgutils==0.3.4
    - tedana==25.0.1
    - templateflow==24.2.2
    - tensorboard==2.17.1
    - tensorboard-data-server==0.7.2
    - tensorflow==2.17.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==3.1.0
    - threadpoolctl==3.6.0
    - tifffile==2025.6.11
    - toml==0.10.2
    - tornado==6.5.1
    - tqdm==4.67.1
    - traits==7.0.2
    - transforms3d==0.4.2
    - typing-extensions==4.14.0
    - tzdata==2025.2
    - universal-pathlib==0.2.6
    - urllib3==2.4.0
    - webcolors==24.11.1
    - werkzeug==3.1.3
    - wheel==0.45.1
    - wrapt==1.17.2
    - xyzservices==2025.4.0
prefix: /cbica/projects/nibs/.conda/envs/processing
