name: curation
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - curl=7.86.0=h2283fc2_1
  - deno=2.1.10=h51487f7_0
  - expat=2.5.0=h27087fc_0
  - gettext=0.21.1=h27087fc_0
  - git=2.38.1=pl5321h8df7355_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h08a2579_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcurl=7.86.0=h2283fc2_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.17=h166bdaf_0
  - liblzma=5.8.1=hb9d3cd8_0
  - libnghttp2=1.47.0=hff17c54_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_0
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=2_h7f98852_perl5
  - python=3.11.0=ha86cf86_0_cpython
  - readline=8.2=h5eee18b_0
  - sqlite=3.49.1=h9eae976_2
  - tk=8.6.13=noxft_h4845f30_101
  - xz=5.2.6=h166bdaf_0
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
    - acres==0.3.0
    - annexremote==1.6.6
    - backports-tarfile==1.2.0
    - boto3==1.40.17
    - botocore==1.40.17
    - certifi==2025.1.31
    - cffi==1.17.1
    - chardet==5.2.0
    - charset-normalizer==3.4.1
    - ci-info==0.3.0
    - click==8.1.8
    - contourpy==1.3.3
    - cryptography==45.0.6
    - cycler==0.12.1
    - datalad==1.2.1
    - dcmstack==0.9.0
    - distro==1.9.0
    - etelemetry==0.3.1
    - fasteners==0.20
    - filelock==3.18.0
    - fonttools==4.60.0
    - git-annex==10.20250721
    - heudiconv==1.3.3
    - humanize==4.13.0
    - idna==3.10
    - importlib-metadata==8.7.0
    - importlib-resources==6.5.2
    - iso8601==2.1.0
    - isodate==0.6.1
    - jaraco-classes==3.4.0
    - jaraco-context==6.0.1
    - jaraco-functools==4.3.0
    - jeepney==0.9.0
    - jmespath==1.0.1
    - joblib==1.4.2
    - keyring==25.6.0
    - keyrings-alt==5.0.2
    - kiwisolver==1.4.9
    - looseversion==1.3.0
    - lxml==5.3.2
    - matplotlib==3.10.6
    - missingno==0.5.2
    - more-itertools==10.7.0
    - msgpack==1.1.1
    - networkx==3.4.2
    - nibabel==5.3.2
    - nilearn==0.11.1
    - nipype==1.10.0
    - numpy==2.2.4
    - packaging==24.2
    - pandas==2.2.3
    - patool==4.0.1
    - pillow==11.3.0
    - pip==25.0
    - platformdirs==4.4.0
    - prov==2.0.1
    - puremagic==1.28
    - pycparser==2.22
    - pydeface==2.0.2
    - pydicom==3.0.1
    - pydot==3.0.4
    - pylibjpeg-libjpeg==2.3.0
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - python-gitlab==6.2.0
    - pytz==2025.2
    - rdflib==6.3.2
    - requests==2.32.3
    - requests-toolbelt==1.0.0
    - s3transfer==0.13.1
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - seaborn==0.13.2
    - secretstorage==3.3.3
    - setuptools==75.8.0
    - simplejson==3.20.1
    - six==1.17.0
    - threadpoolctl==3.6.0
    - tqdm==4.67.1
    - traits==7.0.2
    - typing-extensions==4.13.2
    - tzdata==2025.2
    - urllib3==2.4.0
    - wheel==0.45.1
    - zipp==3.23.0
prefix: /cbica/projects/nibs/.conda/envs/curation
